# Generated by Django 4.1.5 on 2025-03-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('category', models.CharField(choices=[('Personal Stories & Experiences', 'Personal Stories & Experiences'), ('Cultural & Social Commentary', 'Cultural & Social Commentary'), ('Futuristic & Visionary Ideas', 'Futuristic & Visionary Ideas'), ('Inspiration & Motivation', 'Inspiration & Motivation'), ('Philosophical & Deep Thought Pieces', 'Philosophical & Deep Thought Pieces'), ('Book Reviews & Recommendations', 'Book Reviews & Recommendations'), ('Travel & Cultural Exploration', 'Travel & Cultural Exploration')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
